version: "3.8"

networks:
  tech-challenge:
    driver: bridge

services:
  payments-mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - tech-challenge
    ports:
      - 27070:27017
    restart: always
  payment-app:
    build: .
    container_name: "docker-payment-app"
    ports:
      - 8080:8080
