spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: fiap-payments
  profiles:
    active: ${ENVIRONMENT:local}
    server.port: 8080
  data:
    mongodb:
      uri: mongodb://fiap:5z1uCXwBUppuPWmc@mongodb-fiap-tech-challenge-pagamento.cluster-cpsw6q668tdw.us-east-1.docdb.amazonaws.com:27017/fiap?retryWrites=false

  error:
    include-stacktrace: never
payment:
  callback:
    url: mydomain.sample.com/api/pagamentos/callback

pedido:
  uri: https://93kgusvp91.execute-api.us-east-1.amazonaws.com


