name: ci-sonarcloud

on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout do c칩digo do reposit칩rio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar o JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      # Cache do Maven para acelerar builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Rodar testes e gerar cobertura de c칩digo
      - name: Run Maven tests
        run: mvn clean verify -DskipTests=false -Dsonar.junit.reportPaths=target/surefire-reports

      # Executar an치lise no SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 

